### ISSUE TITLE
How to define edges

### ISSUE THREAD

**Issue by dre1080** [seanabrahams/graphql-relay-elixir#11]
For example in the todo relay example: https://github.com/facebook/relay/blob/master/examples/todo/data/schema.js#L140-L149
https://github.com/facebook/relay/blob/master/examples/todo/js/mutations/AddTodoMutation.js

Is this possible yet?

**Comment by seanabrahams** [comment]
@dre1080 Thanks for the example. This will require a small change that I'll push in the next couple of hours. Right now the Connection module doesn't return the edge type alongside the connection type.

**Comment by seanabrahams** [comment]
@dre1080 Turns out it only took a few minutes. I've updated the Connection.new function to return a Map that includes the edge_type alongside the connection_type so that you can do what's in that example. Here's an example from the tests: https://github.com/seanabrahams/graphql-relay-elixir/blob/master/test/support/star_wars/schema.exs#L73

The only thing you need to change is to update any references to connections you've created in the past. So `ship_connection` becomes `ship_connection[:connection_type]` and if you want to access the edge type you use `ship_connection[:edge_type]`.

**Comment by dre1080** [comment]
yes! Thanks! :smile:
